### PR TITLE
Upgrade to 0.2.0

### PR DESCRIPTION
**Pull request by kynan**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kynan** [comment]
@conda-forge-admin please rerender

**Comment by rabernat** [comment]
We now have 3 open PRs for xrft feedstock to try to bump the version.

Let's pick one and try to fix it. @kynan - @roxyboy has been taking a big role in xrft development recently, but he's a novice to conda forge. It would be awesome if you could explain to him (and me!) the basics of how conda forge works and what the responsibilities are of the maintainers.

Possibly related, we are now releasing on pip, so maybe the recipe needs to be modified.

Thanks for your work on this!

**Comment by kynan** [comment]
Sorry for opening another pr, I was under the wrong impression I couldn't push to #5 but actually I can.

Looks like we both got stuck at the same point: `xrft`'s `setup` tries to install dependencies from `setup_requires`. I hope I've been able to fix that now.

Don't mind which pr we end up using but agree we should pick one.

I won't claim to know a lot about how conda-forge works, but happy to try to answer any questions.

**Comment by kynan** [comment]
OK, finally managed to sort out the dependencies. Will merge this so we have the new version up.

Happy to hand this off to @roxyboy in future and will lurk for questions. For the next release I also suggest switching over to pulling the source from PyPI rather than GitHub.

**Comment by roxyboy** [comment]
@kynan Thank you for sorting this out! I'll have to look through your PR to see how you did it.

**Pull request merged**
